'use strict';

const fs = require('fs');
const path = require('path');

const STATE_DIR = path.join(__dirname, 'state');
const MASTER_STATE_PATH = path.join(STATE_DIR, 'master_state.json');
const EVENT_LOG_PATH = path.join(STATE_DIR, 'event_log.jsonl');
const OPS_SUMMARY_PATH = path.join(STATE_DIR, 'ops_summary.md');
const CHECKPOINTS_DIR = path.join(STATE_DIR, 'checkpoints');

// ── Ensure directories exist ──────────────────────────────────────────
function ensureDirs() {
  for (const dir of [STATE_DIR, CHECKPOINTS_DIR]) {
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  }
}

// ── Default master state ──────────────────────────────────────────────
function defaultState() {
  return {
    version: 1,
    current_objective: 'idle',
    active_tasks: [],
    recent_decisions: [],
    current_agents: {
      dellv2: { status: 'unknown', last_seen: null, current_action: null },
      claude: { status: 'unknown', last_seen: null, current_action: null }
    },
    open_blockers: [],
    file_changes: [],
    memory_state: {
      durable_facts: [],
      session_facts: [],
      assumptions: [],
      unresolved_questions: []
    },
    last_updated_by: null,
    last_updated_at: null,
    recovery_instructions: 'Load master_state.json, read latest checkpoint, tail event_log.jsonl for recent events, then resume from last successful action.',
    session_meta: {
      mission: null,
      workflow: null,
      current_step: null,
      pending_next: [],
      last_successful_action: null,
      last_failed_action: null,
      retry_count: 0
    }
  };
}

// ── Load / Save master state ──────────────────────────────────────────
function loadState() {
  ensureDirs();
  try {
    if (fs.existsSync(MASTER_STATE_PATH)) {
      return JSON.parse(fs.readFileSync(MASTER_STATE_PATH, 'utf8'));
    }
  } catch (e) {
    console.error('[SYNC] Failed to load master state, using default:', e.message);
  }
  const state = defaultState();
  saveState(state, 'system');
  return state;
}

function saveState(state, updatedBy) {
  ensureDirs();
  state.last_updated_by = updatedBy || 'unknown';
  state.last_updated_at = new Date().toISOString();
  state.version = (state.version || 0);
  fs.writeFileSync(MASTER_STATE_PATH, JSON.stringify(state, null, 2));
}

// ── Event log (append-only) ───────────────────────────────────────────
function logEvent(event) {
  ensureDirs();
  const entry = {
    timestamp: new Date().toISOString(),
    source_agent: event.source || 'unknown',
    event_type: event.type || 'info',
    priority: event.priority || 'normal',
    task_id: event.task_id || null,
    file_paths: event.files || [],
    summary: event.summary || '',
    detailed_context: event.detail || null,
    result: event.result || null,
    next_action: event.next_action || null,
    status: event.status || null
  };
  fs.appendFileSync(EVENT_LOG_PATH, JSON.stringify(entry) + '\n');
  return entry;
}

function readRecentEvents(count = 20) {
  ensureDirs();
  if (!fs.existsSync(EVENT_LOG_PATH)) return [];
  const lines = fs.readFileSync(EVENT_LOG_PATH, 'utf8').trim().split('\n').filter(Boolean);
  const recent = lines.slice(-count);
  return recent.map(l => { try { return JSON.parse(l); } catch { return null; } }).filter(Boolean);
}

// ── Ops summary (human-readable) ─────────────────────────────────────
function writeOpsSummary(state) {
  ensureDirs();
  const now = new Date().toISOString();
  const events = readRecentEvents(10);
  const eventLines = events.map(e =>
    `- [${e.timestamp.slice(11, 19)}] **${e.source_agent}** ${e.event_type}: ${e.summary}`
  ).join('\n');

  const blockerLines = (state.open_blockers || []).map(b => `- ${b}`).join('\n') || '- None';
  const taskLines = (state.active_tasks || []).map(t =>
    `- [${t.status || '?'}] ${t.id || '?'}: ${t.summary || t.description || '?'} (owner: ${t.owner || '?'})`
  ).join('\n') || '- None';

  const md = `# Operations Summary
> Auto-generated by Memory Sync Bot | Updated: ${now}

## Current Objective
${state.current_objective || 'None set'}

## Agent Status
| Agent | Status | Last Seen | Current Action |
|-------|--------|-----------|----------------|
| DellV2 | ${state.current_agents.dellv2.status} | ${state.current_agents.dellv2.last_seen || 'never'} | ${state.current_agents.dellv2.current_action || 'idle'} |
| Claude | ${state.current_agents.claude.status} | ${state.current_agents.claude.last_seen || 'never'} | ${state.current_agents.claude.current_action || 'idle'} |

## Active Tasks
${taskLines}

## Last 10 Events
${eventLines || '- No events yet'}

## Open Blockers
${blockerLines}

## Session Meta
- **Mission:** ${state.session_meta?.mission || 'none'}
- **Workflow:** ${state.session_meta?.workflow || 'none'}
- **Current Step:** ${state.session_meta?.current_step || 'none'}
- **Last Success:** ${state.session_meta?.last_successful_action || 'none'}
- **Last Failure:** ${state.session_meta?.last_failed_action || 'none'}
- **Retry Count:** ${state.session_meta?.retry_count || 0}

## Next Recommended Action
${(state.session_meta?.pending_next || []).map(a => `- ${a}`).join('\n') || '- Await user input'}

## Recovery Instructions
${state.recovery_instructions || 'Load master_state.json and read event_log.jsonl'}
`;

  fs.writeFileSync(OPS_SUMMARY_PATH, md);
}

// ── Checkpoints ───────────────────────────────────────────────────────
function createCheckpoint(state, reason) {
  ensureDirs();
  const ts = new Date().toISOString().replace(/[:.]/g, '-');
  const cpPath = path.join(CHECKPOINTS_DIR, `${ts}.json`);
  const checkpoint = {
    ...state,
    _checkpoint_reason: reason || 'periodic',
    _checkpoint_time: new Date().toISOString(),
    _recent_events: readRecentEvents(20)
  };
  fs.writeFileSync(cpPath, JSON.stringify(checkpoint, null, 2));

  // Prune old checkpoints — keep latest 20
  const files = fs.readdirSync(CHECKPOINTS_DIR).filter(f => f.endsWith('.json')).sort();
  if (files.length > 20) {
    for (const old of files.slice(0, files.length - 20)) {
      try { fs.unlinkSync(path.join(CHECKPOINTS_DIR, old)); } catch {}
    }
  }

  return cpPath;
}

function loadLatestCheckpoint() {
  ensureDirs();
  const files = fs.readdirSync(CHECKPOINTS_DIR).filter(f => f.endsWith('.json')).sort();
  if (files.length === 0) return null;
  try {
    return JSON.parse(fs.readFileSync(path.join(CHECKPOINTS_DIR, files[files.length - 1]), 'utf8'));
  } catch { return null; }
}

// ── Drift detection ───────────────────────────────────────────────────
function detectDrift(state) {
  const issues = [];
  const now = Date.now();
  const STALE_MS = 5 * 60 * 1000; // 5 minutes

  for (const [name, agent] of Object.entries(state.current_agents || {})) {
    if (agent.last_seen) {
      const age = now - new Date(agent.last_seen).getTime();
      if (age > STALE_MS && agent.status === 'active') {
        issues.push({
          type: 'stale_agent',
          agent: name,
          last_seen: agent.last_seen,
          age_ms: age,
          message: `${name} marked active but last seen ${Math.round(age / 1000)}s ago`
        });
      }
    }
  }

  // Check for tasks stuck in 'active' too long
  for (const task of (state.active_tasks || [])) {
    if (task.status === 'active' && task.started_at) {
      const age = now - new Date(task.started_at).getTime();
      if (age > 30 * 60 * 1000) { // 30 min
        issues.push({
          type: 'stuck_task',
          task_id: task.id,
          age_ms: age,
          message: `Task ${task.id} active for ${Math.round(age / 60000)}m`
        });
      }
    }
  }

  if (issues.length > 0) {
    logEvent({
      source: 'sync-bot',
      type: 'drift_detected',
      priority: 'high',
      summary: `Drift: ${issues.map(i => i.message).join('; ')}`,
      detail: issues
    });
  }

  return issues;
}

// ── Handoff note ──────────────────────────────────────────────────────
function writeHandoff(agent, note) {
  const state = loadState();
  const handoff = {
    from: agent,
    at: new Date().toISOString(),
    what_was_done: note.done || '',
    current_state: note.state || '',
    what_remains: note.remaining || '',
    next_action: note.next || '',
    warnings: note.warnings || []
  };

  logEvent({
    source: agent,
    type: 'handoff',
    priority: 'high',
    summary: `Handoff from ${agent}: ${note.done || 'task update'}`,
    detail: handoff,
    next_action: note.next
  });

  if (state.current_agents[agent]) {
    state.current_agents[agent].status = 'handed_off';
    state.current_agents[agent].last_seen = new Date().toISOString();
  }
  saveState(state, agent);
  writeOpsSummary(state);
  return handoff;
}

// ── Recovery ──────────────────────────────────────────────────────────
function recover() {
  const state = loadState();
  const checkpoint = loadLatestCheckpoint();
  const events = readRecentEvents(30);

  const lastSuccess = events.filter(e => e.status === 'success').pop();
  const lastFailure = events.filter(e => e.status === 'failed' || e.status === 'error').pop();
  const handoffs = events.filter(e => e.event_type === 'handoff');
  const lastHandoff = handoffs.pop();

  const recovery = {
    master_state: state,
    latest_checkpoint: checkpoint ? checkpoint._checkpoint_time : null,
    mission: state.session_meta?.mission || state.current_objective,
    unfinished_tasks: (state.active_tasks || []).filter(t => t.status !== 'done'),
    last_successful_action: lastSuccess?.summary || state.session_meta?.last_successful_action,
    last_failed_action: lastFailure?.summary || state.session_meta?.last_failed_action,
    last_handoff: lastHandoff?.detailed_context || null,
    open_blockers: state.open_blockers || [],
    recommended_next: state.session_meta?.pending_next?.[0] || 'Review state and await user input',
    recent_events_summary: events.slice(-10).map(e => `[${e.timestamp}] ${e.source_agent}: ${e.summary}`)
  };

  logEvent({
    source: 'sync-bot',
    type: 'recovery',
    priority: 'critical',
    summary: 'Recovery invoked — state reconstructed',
    detail: { mission: recovery.mission, unfinished: recovery.unfinished_tasks.length }
  });

  return recovery;
}

// ── High-level sync helpers ───────────────────────────────────────────

// Call this when any meaningful action happens
function sync(agent, action) {
  const state = loadState();

  // Update agent status
  if (state.current_agents[agent]) {
    state.current_agents[agent].status = 'active';
    state.current_agents[agent].last_seen = new Date().toISOString();
    state.current_agents[agent].current_action = action.summary || null;
  }

  // Update session meta
  if (action.mission) state.session_meta.mission = action.mission;
  if (action.workflow) state.session_meta.workflow = action.workflow;
  if (action.step) state.session_meta.current_step = action.step;
  if (action.next) {
    state.session_meta.pending_next = Array.isArray(action.next) ? action.next : [action.next];
  }

  // Track success/failure
  if (action.status === 'success') {
    state.session_meta.last_successful_action = action.summary;
    state.session_meta.retry_count = 0;
  } else if (action.status === 'failed' || action.status === 'error') {
    state.session_meta.last_failed_action = action.summary;
    state.session_meta.retry_count = (state.session_meta.retry_count || 0) + 1;
  }

  // Update objective
  if (action.objective) state.current_objective = action.objective;

  // Track file changes
  if (action.files && action.files.length > 0) {
    for (const f of action.files) {
      const existing = state.file_changes.find(fc => fc.path === f.path);
      if (existing) {
        existing.action = f.action || 'modified';
        existing.at = new Date().toISOString();
        existing.by = agent;
        existing.note = f.note || existing.note;
      } else {
        state.file_changes.push({
          path: f.path,
          action: f.action || 'modified',
          at: new Date().toISOString(),
          by: agent,
          note: f.note || ''
        });
      }
    }
    // Keep only last 50 file changes
    if (state.file_changes.length > 50) {
      state.file_changes = state.file_changes.slice(-50);
    }
  }

  // Track blockers
  if (action.blocker) {
    if (!state.open_blockers.includes(action.blocker)) {
      state.open_blockers.push(action.blocker);
    }
  }
  if (action.resolved_blocker) {
    state.open_blockers = state.open_blockers.filter(b => b !== action.resolved_blocker);
  }

  // Track tasks
  if (action.task) {
    const t = action.task;
    const existing = state.active_tasks.find(at => at.id === t.id);
    if (existing) {
      Object.assign(existing, t);
    } else {
      state.active_tasks.push({
        id: t.id || `task_${Date.now()}`,
        summary: t.summary || t.description,
        owner: t.owner || agent,
        priority: t.priority || 'normal',
        status: t.status || 'queued',
        started_at: t.status === 'active' ? new Date().toISOString() : null,
        dependencies: t.dependencies || [],
        notes: t.notes || ''
      });
    }
    // Clean done tasks older than 1 hour
    const cutoff = Date.now() - 60 * 60 * 1000;
    state.active_tasks = state.active_tasks.filter(at =>
      at.status !== 'done' || (at.completed_at && new Date(at.completed_at).getTime() > cutoff)
    );
  }

  // Track decisions
  if (action.decision) {
    state.recent_decisions.unshift({
      decision: action.decision,
      reason: action.reason || '',
      by: agent,
      at: new Date().toISOString()
    });
    if (state.recent_decisions.length > 20) state.recent_decisions = state.recent_decisions.slice(0, 20);
  }

  // Track memory state
  if (action.fact) {
    const mem = state.memory_state;
    if (action.fact_type === 'durable') {
      if (!mem.durable_facts.includes(action.fact)) mem.durable_facts.push(action.fact);
    } else {
      if (!mem.session_facts.includes(action.fact)) mem.session_facts.push(action.fact);
    }
  }
  if (action.assumption) {
    if (!state.memory_state.assumptions.includes(action.assumption)) {
      state.memory_state.assumptions.push(action.assumption);
    }
  }
  if (action.question) {
    if (!state.memory_state.unresolved_questions.includes(action.question)) {
      state.memory_state.unresolved_questions.push(action.question);
    }
  }
  if (action.resolved_question) {
    state.memory_state.unresolved_questions = state.memory_state.unresolved_questions
      .filter(q => q !== action.resolved_question);
  }

  // Log the event
  logEvent({
    source: agent,
    type: action.type || 'action',
    priority: action.priority || 'normal',
    task_id: action.task_id || action.task?.id,
    files: (action.files || []).map(f => f.path || f),
    summary: action.summary || '',
    detail: action.detail || null,
    result: action.result || null,
    next_action: action.next ? (Array.isArray(action.next) ? action.next[0] : action.next) : null,
    status: action.status || null
  });

  saveState(state, agent);
  writeOpsSummary(state);

  return state;
}

// ── Heartbeat ─────────────────────────────────────────────────────────
let heartbeatInterval = null;

function startHeartbeat(intervalMs = 60000) {
  if (heartbeatInterval) clearInterval(heartbeatInterval);

  heartbeatInterval = setInterval(() => {
    try {
      const state = loadState();
      const drift = detectDrift(state);

      // Auto-checkpoint every 10 heartbeats (default ~10 min)
      if (!startHeartbeat._count) startHeartbeat._count = 0;
      startHeartbeat._count++;
      if (startHeartbeat._count % 10 === 0) {
        createCheckpoint(state, 'periodic heartbeat');
      }

      // Mark stale agents
      const now = Date.now();
      let changed = false;
      for (const [name, agent] of Object.entries(state.current_agents || {})) {
        if (agent.status === 'active' && agent.last_seen) {
          const age = now - new Date(agent.last_seen).getTime();
          if (age > 5 * 60 * 1000) {
            agent.status = 'stale';
            changed = true;
          }
        }
      }

      if (changed) {
        saveState(state, 'sync-bot');
        writeOpsSummary(state);
      }

      if (drift.length > 0) {
        console.log(`[SYNC] Drift detected: ${drift.map(d => d.message).join(', ')}`);
      }
    } catch (e) {
      console.error('[SYNC] Heartbeat error:', e.message);
    }
  }, intervalMs);

  console.log(`[SYNC] Heartbeat started (${intervalMs / 1000}s interval)`);
}

function stopHeartbeat() {
  if (heartbeatInterval) {
    clearInterval(heartbeatInterval);
    heartbeatInterval = null;
    console.log('[SYNC] Heartbeat stopped');
  }
}

// ── Initialize ────────────────────────────────────────────────────────
function init() {
  ensureDirs();
  const state = loadState();

  logEvent({
    source: 'sync-bot',
    type: 'init',
    priority: 'normal',
    summary: 'Memory Sync Bot initialized'
  });

  writeOpsSummary(state);
  createCheckpoint(state, 'init');
  startHeartbeat(60000);

  console.log('[SYNC] Memory Sync Bot ready');
  return state;
}

// ── Exports ───────────────────────────────────────────────────────────
module.exports = {
  init,
  sync,
  loadState,
  saveState,
  logEvent,
  readRecentEvents,
  writeOpsSummary,
  createCheckpoint,
  loadLatestCheckpoint,
  detectDrift,
  writeHandoff,
  recover,
  startHeartbeat,
  stopHeartbeat,
  STATE_DIR,
  MASTER_STATE_PATH,
  EVENT_LOG_PATH,
  OPS_SUMMARY_PATH
};
